production:
  environment: production
  instance_name: "Hinge"
  filestorepath: "/media/exthd/photos/phototank/photofiles"

development:
  environment: development
  instance_name: "dev_Hinge"
  filestorepath: "/Users/martinhinge/Pictures/ROR_PT/phototank"

test:
  environment: test
  instance_name: "test_Hinge"
  filestorepath: "/Users/martinhinge/Pictures/test_migrate"
