production:
  environment: production
  instance_name: "Hinge"
  filestorepath: "/media/exthd/photos/phototank/photofiles"
  filestoreurl: "http://192.168.2.102"

development:
  environment: development
  instance_name: "dev_Hinge"
  filestorepath: "/Users/martinhinge/Pictures/ROR_PT/phototank"
  filestoreurl: "http://localhost:3000"

test:
  environment: test
  instance_name: "test_Hinge"
  filestorepath: "/Users/martinhinge/Pictures/test_migrate"
  filestoreurl: "http://localhost:3000"
