production:
  environment: production
  instance_name: "Hinge"
  filestorepath: "/Users/martinhinge/Downloads/fileserve"

development:
  environment: development
  instance_name: "dev_Hinge"
  filestorepath: "/Users/martinhinge/Pictures/ROR_PT/phototank"
